### ISSUE TITLE
Speed EVs not being imported properly

### ISSUE THREAD

**Issue by guimenezessouza** [ForwardFeed/Redux-Elite-Calc#11]
Pokemon with 252 speed EVs load into the calculator with -4 speed EVs instead. Issue seems to only happen with speed EVs, all of the other EV stats get ported correctly. 
Game Version: Pokemon Elite Redux v1.6.1
![image](https://github.com/ForwardFeed/Redux-Elite-Calc/assets/69261617/23c444b8-65f7-49e5-b223-309ec646d68a)

**Comment by ForwardFeed** [comment]
I cannot reproduce it on my end, that's weird.

**Comment by guimenezessouza** [comment]
sent

**Comment by ForwardFeed** [comment]
Thanks again, it is fixed, it was an issue over javascript being peculiar at handling bitwise operation
