### ISSUE TITLE
Fighting Spirit not detected

### ISSUE THREAD

**Issue by guimenezessouza** [ForwardFeed/Redux-Elite-Calc#12]
Importing a pokemon with fighting spirit will lead into the slot in which fighting spirit was on to be blank. I'd imagine it's because every instance of Fighting Spirit in calc/sr/data/species.ts is misnamed as "Fight Spirit", so maybe changing those instances to "Fighting Spirit" should fix it?

The online dex shows the ability as Fight Spirit if it's an innate, but in game it's treated as Fighting Spirit regardless of being an ability or an innate, that's probably where the confusion started.
![image](https://github.com/ForwardFeed/Redux-Elite-Calc/assets/69261617/a1aac8a0-50f0-4be7-b365-18cabe44561e)
![image](https://github.com/ForwardFeed/Redux-Elite-Calc/assets/69261617/88d21493-62fc-4c0d-8a1d-6d84573a1afd)

**Comment by guimenezessouza** [comment]
Same thing seems to be happening with Electro Surge, which is being referred by the calc code as Electric Surge instead

**Comment by ForwardFeed** [comment]
quick note: The dex and my tooling for importing are two separate codebase. 
my tooling for automatically importing pokemon is https://github.com/ForwardFeed/pokeemerald_to_smogoncalc
And the issue originate from the fact that both ydarissep dex and my script for the internal pokedex use the same file for abilities but the script that import from savefile use another game file.

I have implemented a systematic fix to abilities, thank you  for reporting.
