### ISSUE TITLE
Skill Link

### ISSUE THREAD

**Issue by guimenezessouza** [ForwardFeed/Redux-Elite-Calc#14]
Skill Link only auto sets multi hit abilities to max hits if it's an ability
![image](https://github.com/ForwardFeed/Redux-Elite-Calc/assets/69261617/4e385896-b8fe-43f2-80c7-f4623ded2764)
If it's an innate, it does not work
![image](https://github.com/ForwardFeed/Redux-Elite-Calc/assets/69261617/95e80115-5ead-4593-9f9b-e168a7285df7)

skill link check is at calc/src/move.ts, line 104

**Comment by ForwardFeed** [comment]
fixed thanks.
also this check was in the UI in src/js/panel_move.js line 81
