### ISSUE TITLE
Metallic Defensive Typings

### ISSUE THREAD

**Issue by Choosy9353** [ForwardFeed/Redux-Elite-Calc#2]
Metallic appears to have improperly configured defensive typing. 

EX: Ice Beam into Dhelmise @ 4x effective, should be neutral
EX: Earthquake into Dhelmise @ .25 effective, should be neutral

Flare Blitz into Dhelmise seems to be correct @ x4 though?

**Comment by ForwardFeed** [comment]
Thanks for all your reports, it was a really silly mistake, it is fixed.
