### ISSUE TITLE
Abilities that add a type

### ISSUE THREAD

**Issue by guimenezessouza** [ForwardFeed/Redux-Elite-Calc#32]
They seem to be pretty inconsistent as to when they work

As far as my very limited testing goes, it works on pokemon that have one of the abilities if it's NOT aquatic, and does not work at all if they do not have an ability that adds a type or has aquatic.
I'm pretty sure this worked before so something might've broken it

**Comment by ForwardFeed** [comment]
i'm not sure if i fixed it but at least i have added a third type now, so it's more explicit
