### ISSUE TITLE
Randomized abilities

### ISSUE THREAD

**Issue by Choosy9353** [ForwardFeed/Redux-Elite-Calc#4]
Calc is not configured with randomized abilities in mind for player pokemon. // False, I found the setting. I was silly
Pokemon base abilities can't be changed to any ability. // False, I found the setting. I was silly

Import from save button does not import randomized abilities. // Still true

**Comment by ForwardFeed** [comment]
will fix the randomized ability importation from the savefile.

**Comment by ForwardFeed** [comment]
Fixed, i also sync a bit some gamesettings with the calculator in the way
