### ISSUE TITLE
Boxed Pokemon

### ISSUE THREAD

**Issue by Choosy9353** [ForwardFeed/Redux-Elite-Calc#7]
Importing pokemon from a save file does not load pokemon beyond Box 4.

**Comment by ForwardFeed** [comment]
I indeed set the limit arbitrarily to 60 pokemons, will fix by adding a settings, because nuzlockers use only the first boxes as "alive" pokemon.

**Comment by ForwardFeed** [comment]
Fixed, i added a settings to ask how many pokemon to retrieve
