### ISSUE TITLE
All abilities 1.5.2

### ISSUE THREAD

**Issue by Choosy9353** [ForwardFeed/Redux-Elite-Calc#9]
All abilities option for EliteRedux version 1.5.2 is not present
Still exists for 1.6

**Comment by ForwardFeed** [comment]
I'm confused, how many are missing?

**Comment by Choosy9353** [comment]
The settings panel for 1.5.2 does not have the 'All abilities are selectable' option

**Comment by ForwardFeed** [comment]
oh true, fixed thank you
